const menuToggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
menuToggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');}));
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}})},{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
const form=document.getElementById('contactForm');
const note=document.getElementById('formNote');
form?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const name=data.get('name');const email=data.get('email');const project=data.get('project');const message=data.get('message');const subject=encodeURIComponent(`SHAX portfolio enquiry — ${project}`);const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\nProject type: ${project}\n\nMessage:\n${message}`);window.location.href=`mailto:growmatemgt@gmail.com?subject=${subject}&body=${body}`;note.textContent='Opening your email app…';});
